
const a = `nowadays, i play gregtech on GT New Horizons, which undoubtedly has done the best job integrating the modpack out of anything, and i have to say i am extremely disappointed and left unsatisfied with the direction the mod has taken. all of the machines are mundane and look the same. most are just boring forgettable 1 block structures that are clones of one another but just built with different materials and are completely streamlined. the further you get the more you get punished instead of rewarded, and as you create higher tier machinery you're just paying more for higher efficiency of the same thing that i already have, and there's nothing interesting or attractive about that. the crutch is of course you can't actually process certain things with weaker machines, but that is a very weak and badly designed crutch to compel you to dive further into the machinery tree. this current version of gregtech does not look like it's made by the same person who made the previous version at all. all of the actual interesting and unique structures are completely outshined by these fraudulent tiers, and the balance that was previously created and established was completely thrown out of the window in exchange for excessively complex crafting recipes which can't be designed for any other reason but to waste your time. incorporating all of these tools into recipes was a terrible idea: you have to constantly waste time to remake the tool, you have to constantly waste time putting the tool into the grid, you have to figure out what the hell is going on just to be able to even know how to make the piece that you need... you're expected to have enough inventory space to hold like 6 different tools and all the thousands of different variations of the same materials which the mod now forces you to create(spoilers: you don't), `;

const b = `just to go through a maze of pointless crafting when you could have just dumped all of the raw materials in a pot and reached the same outcome without going through all that trouble. unlike the old IC/gregtech where every crafting component had a purpose, now it seems to just be made to be annoying, boring and completely unnecessary. you know there's a problem when you have more than enough materials to do what you're being asked to do but still don't feel like doing it because it feels pointless. that's bad game design no matter how you look at it, and gregtech has gone from being the thing i turned to to run away from the bad game design of minecraft to being the bad game design i was running away from(and for arguably worse reasons!).`;

msg.reply({
    embed: {
        description: a + b
    }
});
